services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: attendance
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance-backend
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/attendance
    volumes:
      - ./backend/app/images:/app/images
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: attendance-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge
